-- P2-A: auditable PDF workbench runs and step traces.
CREATE TABLE IF NOT EXISTS paper_workbench_run (
    id                       BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id                   VARCHAR(36)   NOT NULL,
    task_id                  VARCHAR(36)   NULL,
    workflow                 VARCHAR(48)   NOT NULL,
    scope                    VARCHAR(24)   NOT NULL,
    status                   VARCHAR(24)   NOT NULL DEFAULT 'PLANNED',
    paper_ids_json           TEXT          NOT NULL,
    request_json             MEDIUMTEXT    NOT NULL,
    plan_json                MEDIUMTEXT    NOT NULL,
    artifact_versions_json   TEXT          NOT NULL,
    evidence_required        BOOLEAN       NOT NULL DEFAULT TRUE,
    max_steps                INT           NOT NULL,
    token_budget             INT           NOT NULL,
    repair_count             INT           NOT NULL DEFAULT 0,
    evidence_count           INT           NOT NULL DEFAULT 0,
    prompt_tokens            INT           NOT NULL DEFAULT 0,
    completion_tokens        INT           NOT NULL DEFAULT 0,
    total_tokens             INT           NOT NULL DEFAULT 0,
    latency_ms               BIGINT        NOT NULL DEFAULT 0,
    result_json              MEDIUMTEXT    NULL,
    error_code               VARCHAR(64)   NULL,
    error_message            VARCHAR(1000) NULL,
    started_at               DATETIME(6)   NULL,
    completed_at             DATETIME(6)   NULL,
    created_at               DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at               DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_workbench_run_id (run_id),
    INDEX idx_workbench_run_created (created_at),
    INDEX idx_workbench_run_status (status),
    INDEX idx_workbench_run_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS paper_workbench_step (
    id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id               VARCHAR(36)   NOT NULL,
    step_index           INT           NOT NULL,
    step_name            VARCHAR(128)  NOT NULL,
    skill_name           VARCHAR(96)   NOT NULL,
    step_kind            VARCHAR(24)   NOT NULL,
    status               VARCHAR(24)   NOT NULL DEFAULT 'PENDING',
    evidence_count       INT           NOT NULL DEFAULT 0,
    retry_count          INT           NOT NULL DEFAULT 0,
    prompt_tokens        INT           NOT NULL DEFAULT 0,
    completion_tokens    INT           NOT NULL DEFAULT 0,
    total_tokens         INT           NOT NULL DEFAULT 0,
    latency_ms           BIGINT        NOT NULL DEFAULT 0,
    input_summary_json   TEXT          NULL,
    output_summary_json  TEXT          NULL,
    error_code           VARCHAR(64)   NULL,
    error_message        VARCHAR(1000) NULL,
    started_at           DATETIME(6)   NULL,
    completed_at         DATETIME(6)   NULL,
    created_at           DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at           DATETIME(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_workbench_step (run_id, step_index),
    INDEX idx_workbench_step_status (run_id, status),
    CONSTRAINT fk_workbench_step_run FOREIGN KEY (run_id)
        REFERENCES paper_workbench_run(run_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
